# This file was generated by GoReleaser. DO NOT EDIT.
cask "khayal" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal_#{version}_darwin_amd64.tar.gz"
      sha256 "1afeadd6f58f8e11c7e1bc0779b4789c2a3244d3bf9ae3a0f65feb52038b5f51"
    end
    on_arm do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal_#{version}_darwin_arm64.tar.gz"
      sha256 "351e135fff6544e963c75a736e6a3beb46db19a051ab4365eb2458ed17daf100"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal_#{version}_linux_amd64.tar.gz"
      sha256 "337d49c92b7ee2dabc3c6a18e5180b8e679a513c9f4bf236e0c9e68f28ec5bdb"
    end
    on_arm do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal_#{version}_linux_arm64.tar.gz"
      sha256 "95202465f17aef7ecaf483cd177524f0a8f28d6a777d1512d1ec3a8fade2aae0"
    end
  end

  name "khayal"
  desc "Your private treasury of thought. Local, secure, yours."
  homepage "https://github.com/rawnaqs/khayal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "khayal"

  service do
    run [opt_bin/"khayal", "start"]
    keep_alive true
  end

  # No zap stanza required

end
