# This file was generated by GoReleaser. DO NOT EDIT.
cask "khayal" do
  name "khayal"
  desc "Your private treasury of thought. Local, secure, yours."
  homepage "https://github.com/rawnaqs/khayal"
  version "0.0.1-pre-release"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "khayal"

  on_macos do
    on_intel do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal_#{version}_darwin_amd64.tar.gz"
      sha256 "a8112eae0bd22dee2cd977bc95b8aae068fafdc576f709e9401878b2014c3c5a"
    end
    on_arm do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal_#{version}_darwin_arm64.tar.gz"
      sha256 "6d2395bb6997a13100eae76660b66aca056d63ea5eefff96d723e1f894ebd539"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal_#{version}_linux_amd64.tar.gz"
      sha256 "7fd0857b87d9596e5200aaa16e1edd9eb607666d4446aba67316cd2e4b77c06a"
    end
    on_arm do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal_#{version}_linux_arm64.tar.gz"
      sha256 "00e1a2ff3af3d1ea8842c548832626f00eb04b3382870824e25e4913fc574758"
    end
  end

  service "run [opt_bin/"khayal", "start"]
keep_alive true
"

  # No zap stanza required
end
