# This file was generated by GoReleaser. DO NOT EDIT.
cask "kl" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal-client_#{version}_darwin_amd64.tar.gz"
      sha256 "c7a07cf9ec6c80a266f5031fc90d037c947f0f053a47184aae5f402013e7d30c"
    end
    on_arm do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal-client_#{version}_darwin_arm64.tar.gz"
      sha256 "4cc59770ef60ed6b6adf06deecd6ac45c0fd650245950b47c1a0354a1bfd08c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal-client_#{version}_linux_amd64.tar.gz"
      sha256 "5104932c97443bfb43f61e90ae61005e7f950317a6bc7aebcfb720725975f891"
    end
    on_arm do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal-client_#{version}_linux_arm64.tar.gz"
      sha256 "c0fd6acc1abde712d18e67f16e52efd8a6af76701319115d8c111711652df612"
    end
  end

  name "kl"
  desc "Khayal CLI client — capture, search, status."
  homepage "https://github.com/rawnaqs/khayal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kl"

  # No zap stanza required

end
