# This file was generated by GoReleaser. DO NOT EDIT.
cask "kl" do
  name "kl"
  desc "Khayal CLI client — capture, search, status."
  homepage "https://github.com/rawnaqs/khayal"
  version "0.0.1-pre-release"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kl"

  on_macos do
    on_intel do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal-client_#{version}_darwin_amd64.tar.gz"
      sha256 "a658da56abe6a3d6019f11e93aa32d15053fa66fbecacad4f287b8f7875ba39f"
    end
    on_arm do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal-client_#{version}_darwin_arm64.tar.gz"
      sha256 "064c2bb600c0214f0b48701a0ff7cafd158d7451441df02c67310a431e952daa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal-client_#{version}_linux_amd64.tar.gz"
      sha256 "066aaa501ad3050135630c03c80b954ac3e549919fa1744e7920c70d12a295f2"
    end
    on_arm do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal-client_#{version}_linux_arm64.tar.gz"
      sha256 "55f767ae1cec2f028a3bd794fe1506c1490e18fa97d411c48d731418271abab2"
    end
  end

  # No zap stanza required
end
