# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Khayal < Formula
  desc "Your private treasury of thought. Local, secure, yours."
  homepage "https://github.com/rawnaqs/khayal"
  version "0.1.3"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rawnaqs/khayal/releases/download/v0.1.3/khayal_0.1.3_darwin_amd64.tar.gz"
      sha256 "b283da81214a1ba6238f81e0dab63078afe5b502cbfa1f5a322fab441220fe28"

      define_method(:install) do
        bin.install "khayal"
        (bash_completion/"khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "bash")
        (zsh_completion/"_khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "zsh")
        (fish_completion/"khayal.fish").write Utils.safe_popen_read(bin/"khayal", "completion", "fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rawnaqs/khayal/releases/download/v0.1.3/khayal_0.1.3_darwin_arm64.tar.gz"
      sha256 "670cd740e4fb4880f539c5ddefd4ed6b42d0244159d145cb98dde54c51b07301"

      define_method(:install) do
        bin.install "khayal"
        (bash_completion/"khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "bash")
        (zsh_completion/"_khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "zsh")
        (fish_completion/"khayal.fish").write Utils.safe_popen_read(bin/"khayal", "completion", "fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rawnaqs/khayal/releases/download/v0.1.3/khayal_0.1.3_linux_amd64.tar.gz"
      sha256 "dbc46cccf13fe58e17663d01b17d001c330f1d64b8de3afe02385a0ae4a7ee32"
      define_method(:install) do
        bin.install "khayal"
        (bash_completion/"khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "bash")
        (zsh_completion/"_khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "zsh")
        (fish_completion/"khayal.fish").write Utils.safe_popen_read(bin/"khayal", "completion", "fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rawnaqs/khayal/releases/download/v0.1.3/khayal_0.1.3_linux_arm64.tar.gz"
      sha256 "c88e65b62c38695a00de910d7b68389af3f64f873a70df5bed9ed5244c8eba1e"
      define_method(:install) do
        bin.install "khayal"
        (bash_completion/"khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "bash")
        (zsh_completion/"_khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "zsh")
        (fish_completion/"khayal.fish").write Utils.safe_popen_read(bin/"khayal", "completion", "fish")
      end
    end
  end

  service do
    run [opt_bin/"khayal", "start"]
    keep_alive true
    log_path var/"log/khayal.log"
    error_log_path var/"log/khayal.err.log"
  end
end
