# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Khayal < Formula
  desc "Your private treasury of thought. Local, secure, yours."
  homepage "https://github.com/rawnaqs/khayal"
  version "0.1.6"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rawnaqs/khayal/releases/download/v0.1.6/khayal_0.1.6_darwin_amd64.tar.gz"
      sha256 "3e21c97e842e44ee3b392a6ab68dce11d3cac21fbf7e29a7b3325cce51a069ee"

      define_method(:install) do
        bin.install "khayal"
        (bash_completion/"khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "bash")
        (zsh_completion/"_khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "zsh")
        (fish_completion/"khayal.fish").write Utils.safe_popen_read(bin/"khayal", "completion", "fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rawnaqs/khayal/releases/download/v0.1.6/khayal_0.1.6_darwin_arm64.tar.gz"
      sha256 "64e5505ffc99958d985984e550fc23e01104db6b8f4222409800f2e854ca92c2"

      define_method(:install) do
        bin.install "khayal"
        (bash_completion/"khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "bash")
        (zsh_completion/"_khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "zsh")
        (fish_completion/"khayal.fish").write Utils.safe_popen_read(bin/"khayal", "completion", "fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rawnaqs/khayal/releases/download/v0.1.6/khayal_0.1.6_linux_amd64.tar.gz"
      sha256 "5431649ab13a9fb9996dbe953a9477d118d8e8371874703d5e9d07e2877211ba"
      define_method(:install) do
        bin.install "khayal"
        (bash_completion/"khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "bash")
        (zsh_completion/"_khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "zsh")
        (fish_completion/"khayal.fish").write Utils.safe_popen_read(bin/"khayal", "completion", "fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rawnaqs/khayal/releases/download/v0.1.6/khayal_0.1.6_linux_arm64.tar.gz"
      sha256 "7b758ab3ac364a40856c3bd6f62b82b69af6a24ddb01415f3992c053b8b89be8"
      define_method(:install) do
        bin.install "khayal"
        (bash_completion/"khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "bash")
        (zsh_completion/"_khayal").write Utils.safe_popen_read(bin/"khayal", "completion", "zsh")
        (fish_completion/"khayal.fish").write Utils.safe_popen_read(bin/"khayal", "completion", "fish")
      end
    end
  end

  def caveats
    <<~EOS
      After installation, run `khayal init` to set up your vault and generate an auth token.
      Then start the server with:
        khayal start
      Or run as a background service:
        brew services start khayal
    EOS
  end

  service do
    run [bin/"khayal", "start"]
    keep_alive true
    log_path var/"log/khayal.log"
    error_log_path var/"log/khayal.err.log"
  end
end
