# This file was generated by GoReleaser. DO NOT EDIT.
cask "khayal" do
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal_#{version}_darwin_amd64.tar.gz"
      sha256 "489f5bde896db0f03772d5b5f36d08cae8ef76c314d967a43b1fdf5a3e0d0139"
    end
    on_arm do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal_#{version}_darwin_arm64.tar.gz"
      sha256 "8be6df1edb01f34224d534f07eb3f8d347fa7c93093359f7b51e78991ff7921f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal_#{version}_linux_amd64.tar.gz"
      sha256 "062230a54101e16cb87ab026f90413c2c54a75fb89344341d429705b1be90744"
    end
    on_arm do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal_#{version}_linux_arm64.tar.gz"
      sha256 "be1a009d31acd53a8219823a1def2c9f9a959319c072ea8062799e0bb347f137"
    end
  end

  name "khayal"
  desc "Your private treasury of thought. Local, secure, yours."
  homepage "https://github.com/rawnaqs/khayal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "khayal"
  generate_completions_from_executable "khayal",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  service "run [opt_bin/"khayal", "start"]
keep_alive true
log_path var/"log/khayal.log"
error_log_path var/"log/khayal.err.log"
"

  # No zap stanza required

end
