# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kl < Formula
  desc "Khayal CLI client — capture, search, status."
  homepage "https://github.com/rawnaqs/khayal"
  version "1.1.1"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rawnaqs/khayal/releases/download/v1.1.1/khayal-client_1.1.1_darwin_amd64.tar.gz"
      sha256 "071ec1703543ef72bb0a96de8bfb1aacf66a93599618ddcb8bc9c43d69539c7e"

      define_method(:install) do
        bin.install "kl"
        (bash_completion/"kl").write Utils.safe_popen_read(bin/"kl", "completion", "bash")
        (zsh_completion/"_kl").write Utils.safe_popen_read(bin/"kl", "completion", "zsh")
        (fish_completion/"kl.fish").write Utils.safe_popen_read(bin/"kl", "completion", "fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rawnaqs/khayal/releases/download/v1.1.1/khayal-client_1.1.1_darwin_arm64.tar.gz"
      sha256 "d6ffb28dd4e50dcacbb5942dc3d5db1952e871a7e7550baa63d914f200cf36ac"

      define_method(:install) do
        bin.install "kl"
        (bash_completion/"kl").write Utils.safe_popen_read(bin/"kl", "completion", "bash")
        (zsh_completion/"_kl").write Utils.safe_popen_read(bin/"kl", "completion", "zsh")
        (fish_completion/"kl.fish").write Utils.safe_popen_read(bin/"kl", "completion", "fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rawnaqs/khayal/releases/download/v1.1.1/khayal-client_1.1.1_linux_amd64.tar.gz"
      sha256 "197aead43516bdecb396005f10d5163ddfd74d7749f45e81b807de4909dd8cc6"
      define_method(:install) do
        bin.install "kl"
        (bash_completion/"kl").write Utils.safe_popen_read(bin/"kl", "completion", "bash")
        (zsh_completion/"_kl").write Utils.safe_popen_read(bin/"kl", "completion", "zsh")
        (fish_completion/"kl.fish").write Utils.safe_popen_read(bin/"kl", "completion", "fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rawnaqs/khayal/releases/download/v1.1.1/khayal-client_1.1.1_linux_arm64.tar.gz"
      sha256 "218196626c539b5042b53382756d36841aaa58b307f9d9727c41cdcb47fae60c"
      define_method(:install) do
        bin.install "kl"
        (bash_completion/"kl").write Utils.safe_popen_read(bin/"kl", "completion", "bash")
        (zsh_completion/"_kl").write Utils.safe_popen_read(bin/"kl", "completion", "zsh")
        (fish_completion/"kl.fish").write Utils.safe_popen_read(bin/"kl", "completion", "fish")
      end
    end
  end

  def caveats
    <<~EOS
      After installation, run `kl init` to connect to a running khayal server.
    EOS
  end
end
