# This file was generated by GoReleaser. DO NOT EDIT.
cask "kl" do
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal-client_#{version}_darwin_amd64.tar.gz"
      sha256 "9feafe0c3270efffdf48790ea3f02b856b7db5575febaa010a184787c09a7ff0"
    end
    on_arm do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal-client_#{version}_darwin_arm64.tar.gz"
      sha256 "26b106ce2b4f9dff597fe6d70ddba022a589fd0a47ddd020c9eee18d5db151af"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal-client_#{version}_linux_amd64.tar.gz"
      sha256 "d0ce411719bc3393a8318af37530b5fd74dd1a8fd6a67d72794707f6f9203a72"
    end
    on_arm do
      url "https://github.com/rawnaqs/khayal/releases/download/v#{version}/khayal-client_#{version}_linux_arm64.tar.gz"
      sha256 "f3910cb677a3c5560195581ac47142da4a791a014bb27e560cd9ed9e2a921891"
    end
  end

  name "kl"
  desc "Khayal CLI client — capture, search, status."
  homepage "https://github.com/rawnaqs/khayal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kl"
  generate_completions_from_executable "kl",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
