# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kl < Formula
  desc "Khayal CLI client — capture, search, status."
  homepage "https://github.com/rawnaqs/khayal"
  version "1.3.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rawnaqs/khayal/releases/download/v1.3.0/khayal-client_1.3.0_darwin_amd64.tar.gz"
      sha256 "9531391d9bd68774d0e826579c3f410624f16f9589cbf85a267922aa771041ac"

      define_method(:install) do
        bin.install "kl"
        (bash_completion/"kl").write Utils.safe_popen_read(bin/"kl", "completion", "bash")
        (zsh_completion/"_kl").write Utils.safe_popen_read(bin/"kl", "completion", "zsh")
        (fish_completion/"kl.fish").write Utils.safe_popen_read(bin/"kl", "completion", "fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rawnaqs/khayal/releases/download/v1.3.0/khayal-client_1.3.0_darwin_arm64.tar.gz"
      sha256 "a98479a8380ee5773d70c756007aca69e1070168e4508165475db1189fae9486"

      define_method(:install) do
        bin.install "kl"
        (bash_completion/"kl").write Utils.safe_popen_read(bin/"kl", "completion", "bash")
        (zsh_completion/"_kl").write Utils.safe_popen_read(bin/"kl", "completion", "zsh")
        (fish_completion/"kl.fish").write Utils.safe_popen_read(bin/"kl", "completion", "fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rawnaqs/khayal/releases/download/v1.3.0/khayal-client_1.3.0_linux_amd64.tar.gz"
      sha256 "ddfc203a42fef420d40550a9c1b560d495ed4cb80008aa3241c47ade9c010e4d"
      define_method(:install) do
        bin.install "kl"
        (bash_completion/"kl").write Utils.safe_popen_read(bin/"kl", "completion", "bash")
        (zsh_completion/"_kl").write Utils.safe_popen_read(bin/"kl", "completion", "zsh")
        (fish_completion/"kl.fish").write Utils.safe_popen_read(bin/"kl", "completion", "fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rawnaqs/khayal/releases/download/v1.3.0/khayal-client_1.3.0_linux_arm64.tar.gz"
      sha256 "c12ac90ff80cb4f6a4a837c6a69b45abc9089bf2faf3e52504e26850ae91092d"
      define_method(:install) do
        bin.install "kl"
        (bash_completion/"kl").write Utils.safe_popen_read(bin/"kl", "completion", "bash")
        (zsh_completion/"_kl").write Utils.safe_popen_read(bin/"kl", "completion", "zsh")
        (fish_completion/"kl.fish").write Utils.safe_popen_read(bin/"kl", "completion", "fish")
      end
    end
  end

  def caveats
    <<~EOS
      After installation, run `kl init` to connect to a running khayal server.
    EOS
  end
end
